name: Tests

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./app/

        strategy:
            matrix:
                python-version: [3.8, 3.9]

        env:
            MODE: ${{ secrets.MODE }}

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}

            
            - name: Setup Cache
              uses: actions/cache@v4.0.2
              with:
                path: ~/.cache/pip
                key: ${{ hashfiles('main.py') }}-${{ hashfiles('requirements.txt') }}


            - name: Install dependencies
              run: |
               python -m pip install --upgrade pip
               pip install -r ../requirements.txt

            - name: Test App Code
              run: python ./main_test.py

            - name: AI Code Review Action
              uses: freeedcom/ai-codereviewer@v2.7.0
        
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                OPENAI_API_MODEL: "gpt-3.5-turbo" 
                exclude: "**/*.json, **/*.md" 



        
